[package]
name = "pop"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
rusqlite = "0.31" 
rayon = "1.8"       
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
regex = "1.10"
anyhow = "1.0"

